import React from "react"
import { ButtonDanger } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonDanger,
  "https://www.figma.com/design/UYAouoXaMoPOyxgM5agLr7/Simple-Design-System--Community-?node-id=185:852",
  {
    props: {
      label: figma.string("Label"),
      iconEnd: figma.instance("Icon End"),
      hasIconEnd: figma.boolean("Has Icon End"),
      hasIconStart: figma.boolean("Has Icon Start"),
      iconStart: figma.instance("Icon Start"),
      variant: figma.enum("Variant", {
        Primary: "danger-primary",
        Subtle: "danger-subtle",
      }),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
    },
    example: (props) => (
      <ButtonDanger 
        variant={props.variant}
        size={props.size}
        isDisabled={props.isDisabled}
      >
        {props.hasIconStart && props.iconStart}
        {props.label}
        {props.hasIconEnd && props.iconEnd}
      </ButtonDanger>
    ),
  },
)
